import Navbar from "./Navbar.jsx";
import Hero from "./Hero.jsx";
import Inquire from "./Inquire.jsx";
import PopularDestinations from "./PopularDestinations.jsx";
import SectionHeader from "./SectionHeader.jsx";
import Button from "./Button.jsx";
import DestinationCard from "./DestinationCard.jsx";
import PopularPackages from "./PopularPackages.jsx";
import PackageCard from "./PackageCard.jsx";
import RememberUs from "./RememberUs.jsx";
import DestinationCatagory from "./DestinationCatagory.jsx";
import SpecialOffers from "./SpecialOffers.jsx";
import SpecialOfferCard from "./SpecialOfferCard.jsx";
import TourGallery from "./TourGallery.jsx";
import HolidaySpecial from "./HolidaySpecial.jsx";
import RecentPosts from "./RecentPosts.jsx";
import RecentPostCard from "./RecentPostCard.jsx";
import FeaturedComments from "./FeaturedComments.jsx";
import CommentSlide from "./CommentSlide.jsx";
import ContactUs from "./ContactUs.jsx";
import Footer from "./Footer.jsx";

export { Navbar, Hero, Inquire, PopularDestinations, SectionHeader, Button, DestinationCard, PopularPackages, PackageCard, RememberUs, DestinationCatagory, SpecialOffers, SpecialOfferCard, TourGallery, HolidaySpecial, RecentPosts, RecentPostCard, FeaturedComments, CommentSlide, ContactUs, Footer };